Student enroll and disenroll
VincTools/Vincool pull request #30
Opened 2017-01-30 23:31 UTC by luisalduucin

2017-01-30 23:55 UTC, imarban requested changes

2017-01-30 23:55 UTC, imarban commented on grails-app/controllers/vincool/SessionController.groovy
> +                    isEnrolled = true
``` isEnrolled = Enrollment.findByStudentAndSession(springSecurityService.getCurrentUser(), session) != null ``` should the trick, isnt' it?

2017-01-31 00:16 UTC, luisalduucin commented on grails-app/controllers/vincool/SessionController.groovy
> +                    isEnrolled = true
Yes, it does !

2017-01-31 00:23 UTC, imarban approved these changes

2017-01-31 00:23 UTC, merged